=== buttonwood-protocol/protocol-lists/src/protocol-list.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://buttonwood-protocol.github.io/protocol-lists/src/protocol-list.schema.json",
  "title": "Buttonwood Protocol List",
  "description": "Schema for lists of protocols that use the Buttonwood protocol",
  "definitions": {
    "Version": {
      "type": "object",
      "description": "The version of the list, used in change detection",
      "examples": [
        {
          "major": 1,
          "minor": 0,
          "patch": 0
        }
      ],
      "additionalProperties": false,
      "properties": {
        "major": {
          "type": "integer",
          "description": "The major version of the list. Must be incremented when protocols are removed from the list or protocol addresses are changed.",
          "minimum": 0,
          "examples": [
            1,
            2
          ]
        },
        "minor": {
          "type": "integer",
          "description": "The minor version of the list. Must be incremented when protocols are added to the list.",
          "minimum": 0,
          "examples": [
            0,
            1
          ]
        },
        "patch": {
          "type": "integer",
          "description": "The patch version of the list. Must be incremented for any changes to the list.",
          "minimum": 0,
          "examples": [
            0,
            1
          ]
        }
      },
      "required": [
        "major",
        "minor",
        "patch"
      ]
    },
    "TagIdentifier": {
      "type": "string",
      "description": "The unique identifier of a tag",
      "minLength": 1,
      "maxLength": 10,
      "pattern": "^[\\w]+$",
      "examples": [
        "compound",
        "stablecoin"
      ]
    },
    "TagDefinition": {
      "type": "object",
      "description": "Definition of a tag that can be associated with a protocol via its identifier",
      "additionalProperties": false,
      "properties": {
        "name": {
          "type": "string",
          "description": "The name of the tag",
          "pattern": "^[ \\w]+$",
          "minLength": 1,
          "maxLength": 20
        },
        "description": {
          "type": "string",
          "description": "A user-friendly description of the tag",
          "pattern": "^[ \\w\\.,:]+$",
          "minLength": 1,
          "maxLength": 200
        }
      },
      "required": [
        "name",
        "description"
      ],
      "examples": [
        {
          "name": "Stablecoin",
          "description": "A token with value pegged to another asset"
        }
      ]
    },
    "Address": {
      "type": "string",
      "description": "The checksummed address on the specified chain ID",
      "pattern": "^0x[a-fA-F0-9]{40}$",
      "examples": [
        "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48"
      ]
    },
    "Name": {
      "type": "string",
      "description": "The name of this address or protocol",
      "minLength": 1,
      "maxLength": 40,
      "examples": [
        "Buttonwood"
      ]
    },
    "ImageURI": {
      "type": "string",
      "description": "A URI for an image to associate with this address or protocol. Recommend SVG or PNG of size 256x256",
      "oneOf": [
        {
          "format": "uri"
        },
        {
          "pattern": "^assets/"
        }
      ],
      "examples": [
        "ipfs://QmXfzKRvjZz3u5JRgC4v5mGVbm9ahrUiB4DgzHBsnWbTMM",
        "assets/protocols/ampleforth/logo.png"
      ]
    },
    "Homepage": {
      "type": "string",
      "description": "A URI for a website to associate with this address or protocol",
      "format": "uri",
      "examples": [
        "https://button.foundation/"
      ]
    },
    "ProtocolAddressInfo": {
      "type": "object",
      "description": "Metadata for a protocol controlled address",
      "properties": {
        "name": {
          "$ref": "#/definitions/Name"
        },
        "imageURI": {
          "$ref": "#/definitions/ImageURI"
        },
        "homepage": {
          "$ref": "#/definitions/Homepage"
        }
      },
      "additionalProperties": false
    },
    "ProtocolChainInfo": {
      "type": "object",
      "properties": {
        "auctionCreators": {
          "type": "array",
          "description": "An array of addresses that are controlled by the protocol and used to create auctions on this chain",
          "items": {
            "$ref": "#/definitions/Address"
          },
          "maxItems": 1000,
          "examples": [
            "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48"
          ]
        },
        "bondCreators": {
          "type": "array",
          "description": "An array of addresses that are controlled by the protocol and used to create bonds on this chain",
          "items": {
            "$ref": "#/definitions/Address"
          },
          "maxItems": 1000,
          "examples": [
            "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48"
          ]
        }
      },
      "additionalProperties": false
    },
    "ProtocolInfo": {
      "type": "object",
      "description": "Metadata for a protocol",
      "properties": {
        "name": {
          "$ref": "#/definitions/Name"
        },
        "imageURI": {
          "$ref": "#/definitions/ImageURI"
        },
        "homepage": {
          "$ref": "#/definitions/Homepage"
        },
        "chains": {
          "type": "object",
          "description": "A map of the chain ID to the protocol data related to that chain",
          "patternProperties": {
            "^[1-9][0-9]*$": {
              "$ref": "#/definitions/ProtocolChainInfo"
            }
          },
          "additionalProperties": false
        },
        "overrides": {
          "type": "object",
          "description": "A map of an address specified in ProtocolChainInfo to properties that override the base protocol metadata",
          "propertyNames": {
            "$ref": "#/definitions/Address"
          },
          "patternProperties": {
            "": {
              "$ref": "#/definitions/ProtocolAddressInfo"
            }
          }
        }
      },
      "required": [
        "name",
        "chains"
      ],
      "additionalProperties": false
    }
  },
  "type": "object",
  "properties": {
    "name": {
      "type": "string",
      "description": "The name of the protocol list",
      "minLength": 1,
      "maxLength": 30,
      "pattern": "^[\\w ]+$",
      "examples": [
        "My Protocol List"
      ]
    },
    "timestamp": {
      "type": "string",
      "format": "date-time",
      "description": "The timestamp of this list version; i.e. when this immutable version of the list was created"
    },
    "version": {
      "$ref": "#/definitions/Version"
    },
    "protocols": {
      "type": "array",
      "description": "The protocols included in the list",
      "items": {
        "$ref": "#/definitions/ProtocolInfo"
      },
      "minItems": 1,
      "maxItems": 10000
    },
    "keywords": {
      "type": "array",
      "description": "Keywords associated with the contents of the list; may be used in list discoverability",
      "items": {
        "type": "string",
        "description": "A keyword to describe the contents of the list",
        "minLength": 1,
        "maxLength": 20,
        "pattern": "^[\\w ]+$",
        "examples": [
          "compound",
          "lending",
          "personal tokens"
        ]
      },
      "maxItems": 20,
      "uniqueItems": true
    },
    "tags": {
      "type": "object",
      "description": "A mapping of tag identifiers to their name and description",
      "propertyNames": {
        "$ref": "#/definitions/TagIdentifier"
      },
      "additionalProperties": {
        "$ref": "#/definitions/TagDefinition"
      },
      "maxProperties": 20,
      "examples": [
        {
          "stablecoin": {
            "name": "Stablecoin",
            "description": "A token with value pegged to another asset"
          }
        }
      ]
    },
    "logoURI": {
      "type": "string",
      "description": "A URI for the logo of the protocol list; prefer SVG or PNG of size 256x256",
      "format": "uri",
      "examples": [
        "ipfs://QmXfzKRvjZz3u5JRgC4v5mGVbm9ahrUiB4DgzHBsnWbTMM"
      ]
    }
  },
  "required": [
    "name",
    "timestamp",
    "version",
    "protocols"
  ],
  "additionalProperties": false
}

=== buttonwood-protocol/protocol-lists/test/examples/metadata-ignored-changes.protocol-list.json
{
  "name": "Buttonwood",
  "timestamp": "2022-12-20T02:41:06.022Z",
  "version": {
    "major": 1,
    "minor": 0,
    "patch": 1
  },
  "logoURI": "https://buttonwood-protocol.github.io/buttonwood-protocol-list/assets/buttonwood.svg",
  "keywords": [
    "buttonwood",
    "defi"
  ],
  "protocols": [
    {
      "name": "PRL",
      "imageURI": "https://buttonwood-protocol.github.io/buttonwood-protocol-list/assets/protocols/prl/mascot.png",
      "homepage": "https://www.prl.one/",
      "chains": {
        "1": {
          "auctionCreators": [
            "0xd7e86Bd77784217324b4E94AEDc68E5C8227EC2B"
          ],
          "bondCreators": [
            "0xd7e86Bd77784217324b4E94AEDc68E5C8227EC2B"
          ]
        },
        "5": {
          "auctionCreators": [
            "0xfD99d2d103b09F95c3dFc458F57178bF0CD587B1",
            "0xEDBcCA5DfD692bab7656Ab2D4F499B43fA26480B",
            "0xb1Cc73B1610863D51B5b8269b9162237e87679c3"
          ]
        }
      }
    }
  ]
}

=== buttonwood-protocol/protocol-lists/test/examples/upgrade-major2.protocol-list.json
{
  "name": "Buttonwood",
  "timestamp": "2022-11-20T02:41:06.022Z",
  "version": {
    "major": 0,
    "minor": 0,
    "patch": 1
  },
  "logoURI": "https://buttonwood-protocol.github.io/buttonwood-protocol-list/assets/buttonwood.svg",
  "keywords": [
    "buttonwood",
    "defi"
  ],
  "protocols": [
    {
      "name": "PRL2",
      "imageURI": "https://buttonwood-protocol.github.io/buttonwood-protocol-list/assets/protocols/prl/logo.png",
      "homepage": "https://www.prl.one/",
      "chains": {
        "1": {
          "auctionCreators": [
            "0xd7e86Bd77784217324b4E94AEDc68E5C8227EC2B",
            "0x4b4E94AEDc68E5C8227EC2Bd7e86Bd7778421732"
          ],
          "bondCreators": [
            "0xd7e86Bd77784217324b4E94AEDc68E5C8227EC2B"
          ]
        },
        "5": {
          "auctionCreators": [
            "0xfD99d2d103b09F95c3dFc458F57178bF0CD587B1",
            "0xEDBcCA5DfD692bab7656Ab2D4F499B43fA26480B",
            "0xb1Cc73B1610863D51B5b8269b9162237e87679c3"
          ],
          "bondCreators": [
            "0xfD99d2d103b09F95c3dFc458F57178bF0CD587B1",
            "0xEDBcCA5DfD692bab7656Ab2D4F499B43fA26480B",
            "0xb1Cc73B1610863D51B5b8269b9162237e87679c3"
          ]
        }
      },
      "overrides": {
        "0xd7e86Bd77784217324b4E94AEDc68E5C8227EC2B": {
          "name": "PRL: Deployer"
        }
      }
    }
  ]
}
